bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('bank/', views.bank, name='bank'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('<int:pk>/',views.single_customer,name='single_customer'),
    path('transaction/',views.transaction,name='transaction'),
    path('loan/',views.loan,name='loan'),
    path('basic_member/',views.basic_member,name='basic_member'),
    path('update_status/', views.update_status, name='update_status'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
    path('delete_account', views.delete_account, name='delete_account'),
]

bank_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_name = models.CharField(max_length=250)
  

    @classmethod
    def create(cls, user, account_name, balance):
        account = cls()
        account.user = user
        account.account_name = account_name
        account.save()
    
    def __str__(self):
        return f"{self.account_name}"

class UserProfile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(default = 0)
    membership = models.CharField(max_length = 50, default = None)
    role = models.CharField(max_length = 50, default = None)

    @classmethod
    def create(cls, user):
        userprofile = cls()
        userprofile.user = user
        userprofile.save() 

    def __str__(self):
        return f"{self.user}"

class Transaction (models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.IntegerField(default = 0)
    transaction_id = models.CharField(max_length = 50, default = None)
    description = models.CharField(max_length = 250, default = None)
    account_to = models.CharField(max_length = 50, default = None)

    @classmethod
    def create(cls, account):
        transaction = cls()
        transaction.account = account
        transaction.save() 

    def __str__(self):
        return f"{self.account}"


def loan(request):
    return render(request, "bank_app/loan.html")

bank_app/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.contrib.auth.models import User
from .models import Account
from django.http import HttpResponseRedirect
from . import models
from .models import UserProfile
from .models import Transaction
import uuid 

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    if request.method == 'POST':
        Account.create(request.user, request.POST['text'])
  
     
         
    accounts = Account.objects.all().filter(user=request.user)

    context = {
        'accounts': accounts,
        

    }
    return render (request, 'bank_app/index.html', context)

@login_required
def transaction(request):
    my_accounts = Account.objects.all().filter(user=request.user)
    accounts = Account.objects.all()
    ran_number = uuid.uuid4().hex[:6].upper()
    account_name = 2
    transactions = Transaction.objects.all().filter(account=account_name)
  
    
    
    if request.method == 'POST':
        transaction = Transaction()
        account_from = Account.objects.get(account_name=request.POST["from_account"])
        transaction.account = account_from
        transaction.amount = request.POST["amount"]
        transaction.description = request.POST["description"]
        transaction.account_to = request.POST["to_account"]
        transaction.transaction_id = request.POST["transaction_id"]
        transaction.save()
        if transaction:
            transaction = Transaction()
            account_to = Account.objects.get(account_name=request.POST["to_account"])
            transaction.account = account_to
            transaction.amount = request.POST["amount"]
            transaction.description = request.POST["description"]
            transaction.account_to = request.POST["from_account"]
            transaction.transaction_id = request.POST["transaction_id"]
            transaction.save()
    context = {
        'my_accounts': my_accounts,
        'accounts': accounts,
        'ran_number': ran_number,
        'transactions': transactions
    }


    return render (request, 'bank_app/transaction.html', context)






@login_required
def loan(request):
    if request.method == 'POST':
        Account.create(request.user, "Loan")
    return render(request, "bank_app/loan.html")

@login_required
def basic_member(request):
    if request.method == 'POST':
        Account.create(request.user, request.POST['text'])

    accounts = Account.objects.all().filter(user=request.user)
    context = {
        'accounts': accounts,
    }
    return render (request, 'bank_app/basic_member.html', context)

@login_required
def bank(request):
    if request.method == "POST":
        text = request.POST["text"]
        user = User()
        user.username = username
        user.save()

    users = User.objects.all()
    context = {
        'users' : users,
    }
    return render (request, 'bank_app/bank.html', context)

@login_required
def sign_up(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']

        phone = request.POST['phone']
        role = request.POST['role']
        membership = request.POST['membership']

        if password == confirm_password:
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            if user:
                userprofile = UserProfile()
                userprofile.user = user
                userprofile.phone = phone
                userprofile.role = role
                userprofile.membership = membership
                userprofile.save()
                return HttpResponseRedirect(reverse('bank_app:bank'))
            else:
                context = {'error': 'Could not create user - try something else'}
        else:
            context ={'error': 'Passwords do not match.'}
    return render(request, 'bank_app/sign_up.html', context)

@login_required
def single_customer(request, pk):
    user = User.objects.get(pk=pk)
    accounts = Account.objects.filter(user=user)
    context = {
        'user': user,
        'accounts': accounts,
    }
    return render(request, 'bank_app/single_customer.html', context)

@login_required
def update_status(request):
    if request.method == "POST":
        pk = request.POST['pk']
        user = User.objects.get(pk=pk)
        userprofile = get_object_or_404(UserProfile, user=user)
        membership = request.POST['membership']
        if user:
            userprofile.membership = membership
            userprofile.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

bank_app/templates/bank_app/bank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a class="active" href="{% url 'bank_app:bank' %}">Home</a></li>
            <li><a href="{% url 'bank_app:sign_up' %}">Register new customer</a></li>
        </ul>
    </nav>

    <h1>Hello, {{ user.username }}</h1>
    <a href="{% url 'login_app:logout' %}">Logout</a>
    <hr>

    <p>Here are your customers:</p>
    <ul>
        {% for user in users  %}
            <li><a href="/{{user.pk}}">{{ user.username }}</a></li>
        {% endfor %}
    </ul>
    
</body>
</html>

bank_app/templates/bank_app/basic_member.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banking system</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a class="active" href="{% url 'bank_app:index' %}">Home</a></li>
            <li><a href="{% url 'bank_app:transaction' %}">Transfer & Transactions</a></li>
            <li><a href="{% url 'login_app:logout' %}">Logout</a></li>
        </ul>
    </nav>

    <h1>Hi {{ user.username }}</h1>
    <p>Here are your accounts:</p>
    <ul>
    {% for account in accounts  %}
        <li>{{ account.account_name }}</li>
    {% endfor %} 
    </ul>

    <hr />
    <form action="." method="POST">
        <h2>Create a new account</h2>
       {% csrf_token %}
       <input type="text" name="text" placeholder="The name of the account" />
       <button>Create account</button>
    </form>
</body>
</html>

bank_app/templates/bank_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banking system</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a class="active" href="{% url 'bank_app:index' %}">Create Account</a></li>
            <li><a href="{% url 'bank_app:transaction' %}">Transfer & Transactions</a></li>
            <li><a href="{% url 'bank_app:loan' %}">Loan</a></li>
            <li><a href="{% url 'login_app:logout' %}">Logout</a></li>
        </ul>
    </nav>

    <h1>Hi {{ user.username }}</h1>
    <p>Here are your accounts:</p>
    <ul>
    {% for account in accounts  %}
        <li>{{ account.account_name }}</li>
        {% endfor %} 

   



</ul>




    <hr />
    <form action="." method="POST">
        <h2>Create a new account</h2>
       {% csrf_token %}
       <input type="text" name="text" placeholder="The name of the account" />
       <button>Create account</button>
    </form>
</body>
</html>

bank_app/templates/bank_app/loan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loan</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'bank_app:index' %}">Create Account</a></li>
            <li><a href="{% url 'bank_app:transaction' %}">Transfer & Transactions</a></li>
            <li><a class="active" href="{% url 'bank_app:loan' %}">Loan</a></li>
            <li><a href="{% url 'login_app:logout' %}">Logout</a></li>
        </ul>
    </nav>

    <h1>Hi {{ user.username }}</h1>
    
    <form action="." method="POST">
        <h2>Create a loan</h2>
       {% csrf_token %}
       <button>Create a Loan account</button>
    </form>



</body>
</html>

bank_app/templates/bank_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'bank_app:bank' %}">Home</a></li>
            <li><a class="active" href="{% url 'bank_app:sign_up' %}">Register new customer</a></li>
        </ul>
    </nav>
    <h1>Sign up</h1>
    <hr>

    <form action="{% url 'bank_app:sign_up' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="text" name="firstname" placeholder="First Name">
        <input type="text" name="lastname" placeholder="Last Name">
        <input type="password" name="password" placeholder="password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="email" name="email" placeholder="email">

        <input type="tel" name="phone" placeholder="Phone">
        <br>
        <select name="role">
            <option value="customer">Customer</option>
            <option value="employee">Bank employee</option>
        </select>
        <br>
        <select name="membership">
            <option value="basic">Basic</option>
            <option value="silver">Silver</option>
            <option value="gold">Gold</option>
        </select>
        
        <br>
        <input type="submit" value="Create customer">
    </form>
    
</body>
</html>

bank_app/templates/bank_app/single_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'bank_app:bank' %}">Home</a></li>
            <li><a href="{% url 'bank_app:sign_up' %}">Register new customer</a></li>
        </ul>
    </nav>

    <h2>{{ user.userprofile.role }}: {{ user.first_name }} {{ user.last_name }}</h2>
    <div class="basic_info">
        <p>Phone number: {{ user.userprofile.phone }}</p>
        <p>Email Address: {{ user.email }}</p>
        <p>Membership: {{ user.userprofile.membership }}</p>

        <form action="{% url 'bank_app:update_status' %}" method="POST">
            <p>Update membership</p>
           {% csrf_token %}
            <select name="membership">
                <option value="basic">Basic</option>
                <option value="silver">Silver</option>
                <option value="gold">Gold</option>
            </select>
            <input type="hidden" name="pk" value="{{user.pk}}">
            <br>
            <input type="submit" value="Update customer">
        </form>
    </div>
    <hr>

    <div>
        <h3>Accounts associated with this {{ user.userprofile.role }}</h3>
        <ul>
        {% for account in accounts  %}
            <li>{{account.account_name}}</li>
        {% endfor %} 
        </ul>
    </div>

</body>
</html>

bank_app/templates/bank_app/transaction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transaction</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bank_app/style.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'bank_app:index' %}">Create Account</a></li>
            <li><a class="active" href="{% url 'bank_app:transaction' %}">Transfer & Transactions</a></li>
            <li><a href="{% url 'bank_app:loan' %}">Loan</a></li>
            <li><a href="{% url 'login_app:logout' %}">Logout</a></li>
        </ul>
    </nav>

    <h1>Hi {{ user.username }}</h1>

    <div class="row">
    

  
    <div class="transaction">
        <h2>See your transactions:</h2>
    {% for transaction in transactions %}
        <p>From: {{transaction.account}}</p>
        <p>To: {{transaction.account_to}}</p>
        <p>Description: {{transaction.description}}</p>
        <p>Amount: {{transaction.amount}}</p>
        <p>You now have: {{transaction.amount}}</p>
    {% endfor %}
    </div>
 
    <div class="balance">
    <h2>See your balance for each of your accounts:</h2>
    <ul>
        {% for transaction in transactions %}
        <li>{{ transaction.account }} <br> <b>Balance: {{transaction.amount}}</b></li>
        {% endfor %} 



    </ul>
  
</div>


</div>
    <hr>



    <form action="." method="post">
        {% csrf_token %}
        <select name="from_account">
       {% for my_account in my_accounts  %}
            <option value="{{my_account.account_name}}">{{my_account.account_name}}</option>
        {% endfor %}  
        </select>
        <br>
        <input type="number" name="amount" placeholder="Amount">
        <input type="text" name="description" placeholder="Description">
        <select name="to_account">
        {% for account in accounts  %}
            <option value="{{account.account_name}}">{{account.account_name}}</option>
        {% endfor %} 
        </select>
        <input type="hidden" name="transaction_id" value={{ran_number}}>
        <br>
        <input type="submit" value="Transfer">
    </form>

</body>
</html>