bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('bank/', views.bank, name='bank'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('<int:pk>/',views.single_customer,name='single_customer'),
    path('transaction/',views.transaction,name='transaction'),
    path('loan/',views.loan,name='loan'),
    path('basic_member/',views.basic_member,name='basic_member'),
    path('update_status/', views.update_status, name='update_status'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
    path('delete_account', views.delete_account, name='delete_account'),
]

login_app/models.py
from django.db import models

from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.user} - {self.created_timestamp}'

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . import models
import django_rq
from . messaging import email_message




# Create your views here.
def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            if user.userprofile.role == 'employee':
                dj_login(request, user)
                return HttpResponseRedirect(reverse('bank_app:bank'))
            if user.userprofile.membership == 'basic':
                dj_login(request, user)
                return HttpResponseRedirect(reverse('bank_app:basic_member'))

            else:
                dj_login(request, user)
                return HttpResponseRedirect(reverse('bank_app:index'))
        else:
            context = {'error': 'Bad username or password.'}
    return render(request, 'login_app/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))
    
def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret', args=[f'{reset_request.secret}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {'message': 'Please click the link in the email we sent to you.'}
        django_rq.enqueue(email_message, {'email_reciever': email, 'reset_link': url})

    return render(request, 'login_app/password_reset.html', context)


def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/password_reset_form.html', context)


def password_reset_form(request):
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    secret = request.POST['secret']

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(user=user,secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse('login_app:login'))
    context = {'error': 'Something went wrong, try again, don\'t screw up this time!'}
    return render(request, 'login_app/password_reset_form.html', context)


def sign_up(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(username, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {'error': 'Could not create user - try somethig else.'}
        else:
            context = {'error': 'Passwords do not match.'}
    return render(request, 'login_app/sign_up.html', context)


def delete_account(request):
    pass

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf_token" content="{{ csrf_token }}">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
 
    <a href="{% url 'login_app:password_reset' %}">Reset password</a>
    <hr>

    <form action="{% url 'login_app:login' %}" method="POST">
        {% csrf_token %} <!-- Prevents x-site scripting. Good security measure. -->
        <input type="text" name="username" placeholder="Username">
        <br>
        <input type="password" name="password" placeholder="password">
        <br>
        <input type="submit" value="Login">
    </form>
    <hr>
    {% if error %}<p style="color:red;">{{ error }}</p>{% endif %}
    
</body>
</html>

login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf_token" content="{{ csrf_token }}">
    <title>Password Reset</title>
</head>
<body>
    <h1>Password Reset</h1>
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr />
    <form action="{% url 'login_app:password_reset' %}" method="POST">
        {% csrf_token %} <!-- Prevents x-site scripting. Good security measure. -->
        <input type="email" name="email" placeholder="email">
        <input type="submit" value="Reset Password">
    </form>
    <hr />
    {% if message %}{{ message }}{% endif %}
</body>
</html>

login_app/templates/login_app/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf_token" content="{{ csrf_token }}">
    <title>Please Set New Password</title>
</head>
<body>
    <h1>New Password</h1>
    <hr />
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
        {% csrf_token %} <!-- Prevents x-site scripting. Good security measure. -->
        <input type="email" name="email" placeholder="Email Address">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="hidden" name="secret" value="{{ secret }}">
        <input type="submit" value="Set New Password">
    </form>
    <hr />
    {% if error %}{{ error }}{% endif %}
</body>
</html>

login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <h1>Sign Up</h1>
    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr>
    <form action="{% url 'login_app:sign_up' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="User Name">
        <input type="password" name="password" placeholder="Password">
        <input type="password" name="confirm_password" placeholder="Confirm Password">
        <input type="email" name="email" placeholder="Email Address">
        <input type="submit" value="Sign Up">
    </form>
</body>
</html>